#theme = "slick"
#icons = "none"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#f37000"
good_bg = "#000000"
good_fg = "#00ff00"
info_bg = "#000000"
info_fg = "#ff4000"
warning_bg = "#000000"
warning_fg = "#ff0000"
critical_bg = "#ff0000"
critical_fg = "#ffffff"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
bitrate = true
speed_up = false
graph_up = true
speed_down = false
graph_down = true
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "uptime"

[[block]]
block = "disk_space"
path = "/"
alias = "DISK"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "load"
format = "{ {1m} | {5m} | {15m} }"
interval = 1

[[block]]
block = "memory"
format_mem = "{Mug} GB / {MTg} GB ({Mup}%)"
format_swap = "{SUg} GB / {STg} GB ({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 10
critical_mem = 95
critical_swap = 50

[[block]]
block = "battery"
interval = 10
show = "both"

[[block]]
block = "time"
format = "%a %m/%d %R"
interval = 60
